# Generated by Django 4.0.6 on 2022-07-18 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_remove_customer_date_customer_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
