# Generated by Django 4.0.6 on 2022-07-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_customer_dates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
